name: Install Dependencies
description: Install NPM Packages and Playwright Browser with Dependencies

runs:
  using: "composite"
  steps:
    - name: Install NPM Packages
      run: npm install
      shell: bash
    - name: Install Playwright Browser with Dependencies
      run: npx -y playwright install chromium --with-deps
      shell: bash
