name: Install dependencies
description: Install packages & playwright browser with dependencies

runs:
  using: "composite"
  steps:
    - name: Install packages
      run: deno install
      shell: bash
    - name: Install playwright browser with dependencies
      run: deno run -A playwright install chromium --with-deps
      shell: bash
