name: Install dependencies
description: Install packages & playwright browser with dependencies

runs:
  using: "composite"
  steps:
    - name: Install deno
      uses: denoland/setup-deno@v2
      with:
        deno-version: v2.x
    - name: Install packages
      run: deno install
      shell: bash
    - name: Install playwright browser with dependencies
      run: deno run -A npm:playwright install chromium --with-deps
      shell: bash
