name: Auth

on:
  workflow_dispatch:

env:
  DIRECT_URL: ${{secrets.DIRECT_URL}}
  DATABASE_URL: ${{secrets.DATABASE_URL}}

jobs:
  Auth:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        uses: ./.github/workflows/action.yml
      - name: Authenticate
        run: npm run auth
