name: Scrape

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0,12 * * *'

env:
  DIRECT_URL: ${{secrets.DIRECT_URL}}
  DATABASE_URL: ${{secrets.DATABASE_URL}}

jobs:
  Scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install NPM Packages
        run: npm install
      - name: Install Playwright Browser with Dependencies
        run: npx -y playwright install chromium --with-deps
      - name: Scrape
        run: npm run scrape
